import { NextResponse } from "next/server"
import type { NextRequest } from "next/server"

// Direct mapping of exact paths to redirect destinations
// This is much faster than computing the redirects dynamically
const REDIRECT_MAP: Record<string, string> = {
  "/city/alton": "/metronet-state/illinois",
  "/city/burnsville": "/metronet-state/minnesota",
  "/city/elkhart": "/metronet-state/indiana",
  "/city/north-liberty": "/metronet-state/iowa",
  "/city/muscatine": "/metronet-state/iowa",
  "/city/alexandria": "/metronet-state/indiana",
  "/city/erie": "/metronet-state/pennsylvania",
  "/city/louisville": "/metronet-state/kentucky",
  "/city/fairview-heights": "/metronet-state/illinois",
  "/city/logansport": "/metronet-state/indiana",
  "/city/tyler": "/metronet-state/texas",
  "/city/cedar-falls": "/metronet-state/iowa",
  "/city/albert-lea": "/metronet-state/minnesota",
  "/city/buffalo": "/metronet-state/minnesota",
  "/city/terre-haute": "/metronet-state/indiana",
  "/city/east-peoria": "/metronet-state/illinois",
  "/city/bluffton": "/metronet-state/indiana",
  "/city/canton": "/metronet-state/ohio",
  "/city/mattoon": "/metronet-state/illinois",
  "/city/miami": "/metronet-state/florida",
  "/city/blacksburg": "/metronet-state/virginia",
  "/city/marshalltown": "/metronet-state/iowa",
  "/city/fremont": "/metronet-state/nebraska",
  "/city/adrian": "/metronet-state/michigan",
  "/city/cedar-rapids": "/metronet-state/iowa",
  "/city/fort-myers": "/metronet-state/florida",
  "/city/anderson": "/metronet-state/indiana",
  "/city/highland": "/metronet-state/illinois",
  "/city/bemidji": "/metronet-state/minnesota",
  "/city/seminole": "/metronet-state/florida",
  "/city/owosso": "/metronet-state/michigan",
  "/city/ottumwa": "/metronet-state/iowa",
  "/city/plymouth": "/metronet-state/indiana",
  "/city/brainerd": "/metronet-state/minnesota",
  "/city/clearwater": "/metronet-state/florida",
  "/city/valparaiso": "/metronet-state/indiana",
  "/city/oskaloosa": "/metronet-state/iowa",
  "/city/aurora": "/metronet-state/illinois",
  "/city/granite-city": "/metronet-state/illinois",
  "/city/bedford": "/metronet-state/indiana",
  "/city/avon": "/metronet-state/indiana",
  "/city/boone": "/metronet-state/iowa",
  "/city/cloquet": "/metronet-state/minnesota",
  "/city/asheville": "/metronet-state/north-carolina",
  "/city/ionia": "/metronet-state/michigan",
  "/city/edwardsville": "/metronet-state/illinois",
  "/city/coldwater": "/metronet-state/michigan",
  "/city/boulder": "/metronet-state/colorado",
  "/city/charleston": "/metronet-state/illinois",
  "/city/fort-dodge": "/metronet-state/iowa",
  "/city/martinsville": "/metronet-state/indiana",
  "/city/durham": "/metronet-state/north-carolina",
  "/city/houghton": "/metronet-state/michigan",
  "/city/brooklyn-park": "/metronet-state/minnesota",
  "/city/casselberry": "/metronet-state/florida",
  "/city/murray": "/metronet-state/kentucky",
  "/city/jasper": "/metronet-state/indiana",
  "/city/dubuque": "/metronet-state/iowa",
  "/city/owensboro": "/metronet-state/kentucky",
  "/city/alma": "/metronet-state/michigan",
  "/city/midland": "/metronet-state/michigan",
  "/city/waukee": "/metronet-state/iowa",
  "/city/mount-pleasant": "/metronet-state/michigan",
  "/city/big-rapids": "/metronet-state/michigan",
  "/city/winter-park": "/metronet-state/florida",
  "/city/decatur": "/metronet-state/illinois",
  "/city/burlington": "/metronet-state/iowa",
  "/city/peoria": "/metronet-state/illinois",
  "/city/jackson": "/metronet-state/michigan",
  "/city/crown-point": "/metronet-state/indiana",
  "/city/columbia-city": "/metronet-state/indiana",
  "/city/columbus": "/metronet-state/indiana",
  "/city/cambridge": "/metronet-state/minnesota",
  "/city/battle-creek": "/metronet-state/michigan",
  "/city/kokomo": "/metronet-state/indiana",
  "/city/athens": "/metronet-state/ohio",
  "/city/carbondale": "/metronet-state/illinois",
  "/city/brownsburg": "/metronet-state/indiana",
  "/city/raleigh": "/metronet-state/north-carolina",
  "/city/glen-carbon": "/metronet-state/illinois",
  "/city/fort-collins": "/metronet-state/colorado",
  "/city/fort-wayne": "/metronet-state/indiana",
  "/city/auburn": "/metronet-state/indiana",
  "/city/eau-claire": "/metronet-state/wisconsin",
  "/city/greenfield": "/metronet-state/indiana",
  "/city/effingham": "/metronet-state/illinois",
  "/city/macomb": "/metronet-state/illinois",
  "/city/elizabethtown": "/metronet-state/kentucky",
  "/city/concord": "/metronet-state/north-carolina",
  "/city/cincinnati": "/metronet-state/ohio",
  "/city/pekin": "/metronet-state/illinois",
  "/city/muskegon": "/metronet-state/michigan",
  "/city/winter-springs": "/metronet-state/florida",
  "/city/collinsville": "/metronet-state/illinois",
  "/city/shelbyville": "/metronet-state/indiana",
  "/city/naples": "/metronet-state/florida",
  "/city/danville": "/metronet-state/illinois",
  "/city/belleville": "/metronet-state/illinois",
  "/city/denver": "/metronet-state/colorado",
  "/city/champaign": "/metronet-state/illinois",
  "/city/charlotte": "/metronet-state/north-carolina",
  "/city/tampa": "/metronet-state/florida",
  "/city/ludington": "/metronet-state/michigan",
  "/city/holland": "/metronet-state/michigan",
  "/city/newton": "/metronet-state/iowa",
  "/city/chillicothe": "/metronet-state/illinois",
  "/city/muncie": "/metronet-state/indiana",
  "/city/mishawaka": "/metronet-state/indiana",
  "/city/dixon": "/metronet-state/illinois",
  "/city/kearney": "/metronet-state/nebraska",
  "/city/chicago": "/metronet-state/illinois",
  "/city/grand-haven": "/metronet-state/michigan",
  "/city/goshen": "/metronet-state/indiana",
  "/city/indianola": "/metronet-state/iowa",
  "/city/urbana": "/metronet-state/illinois",
  "/city/bowling-green": "/metronet-state/kentucky",
  "/city/cadillac": "/metronet-state/michigan",
  "/city/kissimmee": "/metronet-state/florida",
  "/city/freeport": "/metronet-state/illinois",
  "/city/angola": "/metronet-state/indiana",
  "/city/grand-island": "/metronet-state/nebraska",
  "/city/saint-charles": "/metronet-state/missouri",
  "/city/michigan-city": "/metronet-state/indiana",

  // Add the /metronet/ redirects
  "/metronet/alton": "/metronet-state/illinois",
  "/metronet/burnsville": "/metronet-state/minnesota",
  "/metronet/elkhart": "/metronet-state/indiana",
  "/metronet/north-liberty": "/metronet-state/iowa",
  "/metronet/muscatine": "/metronet-state/iowa",
  "/metronet/alexandria": "/metronet-state/indiana",
  "/metronet/erie": "/metronet-state/pennsylvania",
  "/metronet/louisville": "/metronet-state/kentucky",
  "/metronet/fairview-heights": "/metronet-state/illinois",
  "/metronet/logansport": "/metronet-state/indiana",
  "/metronet/tyler": "/metronet-state/texas",
  "/metronet/cedar-falls": "/metronet-state/iowa",
  "/metronet/albert-lea": "/metronet-state/minnesota",
  "/metronet/buffalo": "/metronet-state/minnesota",
  "/metronet/terre-haute": "/metronet-state/indiana",
  "/metronet/east-peoria": "/metronet-state/illinois",
  "/metronet/bluffton": "/metronet-state/indiana",
  "/metronet/canton": "/metronet-state/ohio",
  "/metronet/mattoon": "/metronet-state/illinois",
  "/metronet/miami": "/metronet-state/florida",
  "/metronet/blacksburg": "/metronet-state/virginia",
  "/metronet/marshalltown": "/metronet-state/iowa",
  "/metronet/fremont": "/metronet-state/nebraska",
  "/metronet/adrian": "/metronet-state/michigan",
  "/metronet/cedar-rapids": "/metronet-state/iowa",
  "/metronet/fort-myers": "/metronet-state/florida",
  "/metronet/anderson": "/metronet-state/indiana",
  "/metronet/highland": "/metronet-state/illinois",
  "/metronet/bemidji": "/metronet-state/minnesota",
  "/metronet/seminole": "/metronet-state/florida",
  "/metronet/owosso": "/metronet-state/michigan",
  "/metronet/ottumwa": "/metronet-state/iowa",
  "/metronet/plymouth": "/metronet-state/indiana",
  "/metronet/brainerd": "/metronet-state/minnesota",
  "/metronet/clearwater": "/metronet-state/florida",
  "/metronet/valparaiso": "/metronet-state/indiana",
  "/metronet/oskaloosa": "/metronet-state/iowa",
  "/metronet/aurora": "/metronet-state/illinois",
  "/metronet/granite-city": "/metronet-state/illinois",
  "/metronet/bedford": "/metronet-state/indiana",
  "/metronet/avon": "/metronet-state/indiana",
  "/metronet/boone": "/metronet-state/iowa",
  "/metronet/cloquet": "/metronet-state/minnesota",
  "/metronet/asheville": "/metronet-state/north-carolina",
  "/metronet/ionia": "/metronet-state/michigan",
  "/metronet/edwardsville": "/metronet-state/illinois",
  "/metronet/coldwater": "/metronet-state/michigan",
  "/metronet/boulder": "/metronet-state/colorado",
  "/metronet/charleston": "/metronet-state/illinois",
  "/metronet/fort-dodge": "/metronet-state/iowa",
  "/metronet/martinsville": "/metronet-state/indiana",
  "/metronet/durham": "/metronet-state/north-carolina",
  "/metronet/houghton": "/metronet-state/michigan",
  "/metronet/brooklyn-park": "/metronet-state/minnesota",
  "/metronet/casselberry": "/metronet-state/florida",
  "/metronet/murray": "/metronet-state/kentucky",
  "/metronet/jasper": "/metronet-state/indiana",
  "/metronet/dubuque": "/metronet-state/iowa",
  "/metronet/owensboro": "/metronet-state/kentucky",
  "/metronet/alma": "/metronet-state/michigan",
  "/metronet/midland": "/metronet-state/michigan",
  "/metronet/waukee": "/metronet-state/iowa",
  "/metronet/mount-pleasant": "/metronet-state/michigan",
  "/metronet/big-rapids": "/metronet-state/michigan",
  "/metronet/winter-park": "/metronet-state/florida",
  "/metronet/decatur": "/metronet-state/illinois",
  "/metronet/burlington": "/metronet-state/iowa",
  "/metronet/peoria": "/metronet-state/illinois",
  "/metronet/jackson": "/metronet-state/michigan",
  "/metronet/crown-point": "/metronet-state/indiana",
  "/metronet/columbia-city": "/metronet-state/indiana",
  "/metronet/columbus": "/metronet-state/indiana",
  "/metronet/cambridge": "/metronet-state/minnesota",
  "/metronet/battle-creek": "/metronet-state/michigan",
  "/metronet/kokomo": "/metronet-state/indiana",
  "/metronet/athens": "/metronet-state/ohio",
  "/metronet/carbondale": "/metronet-state/illinois",
  "/metronet/brownsburg": "/metronet-state/indiana",
  "/metronet/raleigh": "/metronet-state/north-carolina",
  "/metronet/glen-carbon": "/metronet-state/illinois",
  "/metronet/fort-collins": "/metronet-state/colorado",
  "/metronet/fort-wayne": "/metronet-state/indiana",
  "/metronet/auburn": "/metronet-state/indiana",
  "/metronet/eau-claire": "/metronet-state/wisconsin",
  "/metronet/greenfield": "/metronet-state/indiana",
  "/metronet/effingham": "/metronet-state/illinois",
  "/metronet/macomb": "/metronet-state/illinois",
  "/metronet/elizabethtown": "/metronet-state/kentucky",
  "/metronet/concord": "/metronet-state/north-carolina",
  "/metronet/cincinnati": "/metronet-state/ohio",
  "/metronet/pekin": "/metronet-state/illinois",
  "/metronet/muskegon": "/metronet-state/michigan",
  "/metronet/winter-springs": "/metronet-state/florida",
  "/metronet/collinsville": "/metronet-state/illinois",
  "/metronet/shelbyville": "/metronet-state/indiana",
  "/metronet/naples": "/metronet-state/florida",
  "/metronet/danville": "/metronet-state/illinois",
  "/metronet/belleville": "/metronet-state/illinois",
  "/metronet/denver": "/metronet-state/colorado",
  "/metronet/champaign": "/metronet-state/illinois",
  "/metronet/charlotte": "/metronet-state/north-carolina",
  "/metronet/tampa": "/metronet-state/florida",
  "/metronet/ludington": "/metronet-state/michigan",
  "/metronet/holland": "/metronet-state/michigan",
  "/metronet/newton": "/metronet-state/iowa",
  "/metronet/chillicothe": "/metronet-state/illinois",
  "/metronet/muncie": "/metronet-state/indiana",
  "/metronet/mishawaka": "/metronet-state/indiana",
  "/metronet/dixon": "/metronet-state/illinois",
  "/metronet/kearney": "/metronet-state/nebraska",
  "/metronet/chicago": "/metronet-state/illinois",
  "/metronet/grand-haven": "/metronet-state/michigan",
  "/metronet/goshen": "/metronet-state/indiana",
  "/metronet/indianola": "/metronet-state/iowa",
  "/metronet/urbana": "/metronet-state/illinois",
  "/metronet/bowling-green": "/metronet-state/kentucky",
  "/metronet/cadillac": "/metronet-state/michigan",
  "/metronet/kissimmee": "/metronet-state/florida",
  "/metronet/freeport": "/metronet-state/illinois",
  "/metronet/angola": "/metronet-state/indiana",
  "/metronet/grand-island": "/metronet-state/nebraska",
  "/metronet/saint-charles": "/metronet-state/missouri",
  "/metronet/michigan-city": "/metronet-state/indiana",
}

export function middleware(request: NextRequest) {
  // Get the path to check against our redirect map
  const pathname = request.nextUrl.pathname

  // Check if we have a direct redirect for this path
  const redirectTo = REDIRECT_MAP[pathname]
  if (redirectTo) {
    // Create the redirect URL and return the response
    const redirectUrl = new URL(redirectTo, request.url).toString()
    return NextResponse.redirect(redirectUrl, 301)
  }

  // If no redirect is found, proceed normally
  return NextResponse.next()
}

export const config = {
  // Only match the specific URL patterns we need to redirect
  matcher: ["/city/:path*", "/metronet/:path*"],
}
