export const HOME_FAQS = [
  { q: "How fast is Metronet's fiber internet?", a: "Metronet offers 500 Mbps, 1 Gig, and 2 Gig residential plans, all with symmetrical upload and download speeds — your upload is exactly as fast as your download, which is not the case on cable internet." },
  { q: "How much does Metronet internet cost?", a: "Current pricing through Metroconet is $60/mo for 500 Mbps, $70/mo for 1 Gig, and $80/mo for 2 Gig, all with AutoPay. First Month Free is available for eligible new customers." },
  { q: "Which Metronet plan should I choose?", a: "1 Gig at $70/mo is the mainstream choice for most households running multiple devices, 4K streaming, gaming, and remote work. 500 Mbps suits one or two light users. 2 Gig is only $10/mo more than 1 Gig and is best for large households, heavy uploads, and smart-home setups." },
  { q: "Is there a data cap?", a: "No. Every Metronet plan ordered through Metroconet includes unlimited data with no caps, throttling, or overage charges." },
  { q: "Is there an annual contract?", a: "No annual contract is required on any current Metronet residential plan." },
  { q: "Is Metroconet the same company as Metronet?", a: "No. Metroconet is an independent authorized retailer for new Metronet service. Metronet is the fiber provider; Metroconet helps you compare plans, confirm availability, and place a new service order." },
  { q: "How do I know if Metronet fiber is available at my address?", a: "Enter your zip code in the availability checker on this page or on the Check Availability page. Because fiber is built street by street, final serviceability is confirmed against your exact address during ordering. If service isn't live yet, you can join the waitlist." },
  { q: "What is First Month Free?", a: "First Month Free is Metroconet's current featured promotion for eligible new customers ordering new Metronet service. Offer availability and eligibility may vary by service address and are confirmed during the ordering process." },
  { q: "How long does installation take and what happens?", a: "You choose a preferred install date and time window when you order, and a confirmation follows by email. A technician brings the fiber line to your home, installs the fiber gateway, and gets your Wi-Fi running." },
  { q: "Do I get a router with my plan?", a: "A fiber gateway/router is included with installation so your home is Wi-Fi ready from day one." },
  { q: "Why is fiber better than cable for working from home?", a: "Remote work depends on upload bandwidth for video calls, screen sharing, and file transfers. Cable gives you a fast download and a much slower upload, while fiber is symmetrical — so calls stay clear and uploads finish quickly even when the rest of the house is online." },
  { q: "Do I need to call to order Metronet service?", a: "No. You can compare plans, choose a speed, and complete a new Metronet service order online through Metroconet, including selecting your preferred install date and time window." },
]
